# Generated by Django 3.2.7 on 2021-09-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210928_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Simple User'), (1, 'Admin')], default=0),
        ),
    ]
