# Generated by Django 3.2.7 on 2021-09-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allowed_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
